// ─── Fallback Question Bank ───────────────────────────────────────────────────
// 31 hardcoded questions used when Claude or The One API is unavailable.
// These ensure the game always works even without API keys configured.
// Questions cover all 6 categories and 7 source materials.

import type { TriviaClue } from "@/types/game";

export const FALLBACK_QUESTIONS: TriviaClue[] = [
  // ─── Fellowship & Heroes ──────────────────────────────────────────────────
  {
    id: "fh-200-1",
    category: "Fellowship & Heroes",
    points: 200,
    clue: "This hobbit is tasked with carrying the One Ring from the Shire to Mordor.",
    correct_answer: "Frodo Baggins",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-400-1",
    category: "Fellowship & Heroes",
    points: 400,
    clue: "This loyal hobbit companion of Frodo famously says, 'I can't carry it for you, but I can carry you!'",
    correct_answer: "Samwise Gamgee",
    difficulty: "medium",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-600-1",
    category: "Fellowship & Heroes",
    points: 600,
    clue: "This Ranger of the North is heir to the throne of Gondor and goes by the alias 'Strider' in the films.",
    correct_answer: "Aragorn",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-800-1",
    category: "Fellowship & Heroes",
    points: 800,
    clue: "This Rohirrim captain led Theoden's forces into battle and is Eowyn's uncle.",
    correct_answer: "Eomer",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-1000-1",
    category: "Fellowship & Heroes",
    points: 1000,
    clue: "In Tolkien's books, Aragorn's mother gave him this name meaning 'Hope' in Quenya when he was hidden in Rivendell.",
    correct_answer: "Estel",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // ─── Rings & Dark Powers ──────────────────────────────────────────────────
  {
    id: "rdp-200-1",
    category: "Rings & Dark Powers",
    points: 200,
    clue: "The inscription on the One Ring, spoken in the Black Speech of Mordor, begins with these words.",
    correct_answer: "One Ring to rule them all",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-400-1",
    category: "Rings & Dark Powers",
    points: 400,
    clue: "This creature, once a hobbit named Sméagol, murdered his cousin Déagol to possess the One Ring.",
    correct_answer: "Gollum",
    difficulty: "medium",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-600-1",
    category: "Rings & Dark Powers",
    points: 600,
    clue: "This number of Rings of Power were given to the race of Men, making them susceptible to Sauron's will.",
    correct_answer: "Nine",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-800-1",
    category: "Rings & Dark Powers",
    points: 800,
    clue: "Before being known as Sauron, this was the name of the Maia who served under Aulë the Smith.",
    correct_answer: "Mairon",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-1000-1",
    category: "Rings & Dark Powers",
    points: 1000,
    clue: "This Nazgûl lord, also known as the Witch-king of Angmar, wielded a Morgul-blade that would have turned Frodo into a wraith.",
    correct_answer: "Khamûl (or the Witch-king of Angmar)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // ─── Lands of Middle-earth ────────────────────────────────────────────────
  {
    id: "lme-200-1",
    category: "Lands of Middle-earth",
    points: 200,
    clue: "This peaceful hobbit homeland is where Frodo and Bilbo begin their adventures.",
    correct_answer: "The Shire",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-400-1",
    category: "Lands of Middle-earth",
    points: 400,
    clue: "Helm's Deep, the fortress where Theoden's people make their stand in The Two Towers, is located in this kingdom.",
    correct_answer: "Rohan",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-600-1",
    category: "Lands of Middle-earth",
    points: 600,
    clue: "This ancient elvish realm, ruled by Galadriel and Celeborn, serves as a refuge for the Fellowship after Moria.",
    correct_answer: "Lothlórien",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-800-1",
    category: "Lands of Middle-earth",
    points: 800,
    clue: "The dwarven city of Erebor, home of the Lonely Mountain, was sacked by this dragon and reclaimed by Thorin's company.",
    correct_answer: "Smaug",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-1000-1",
    category: "Lands of Middle-earth",
    points: 1000,
    clue: "This hidden elven city, founded by Turgon in the First Age and not depicted in the films, was destroyed by Morgoth and is the birthplace of Eärendil.",
    correct_answer: "Gondolin",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // ─── Epic Battles & Wars ──────────────────────────────────────────────────
  {
    id: "ebw-200-1",
    category: "Epic Battles & Wars",
    points: 200,
    clue: "This battle, fought at the gates of Mordor, ends when Frodo destroys the One Ring.",
    correct_answer: "Battle of the Black Gate",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-400-1",
    category: "Epic Battles & Wars",
    points: 400,
    clue: "Eowyn famously slays the Witch-king of Angmar during this massive battle on the fields of Gondor.",
    correct_answer: "Battle of the Pelennor Fields",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-600-1",
    category: "Epic Battles & Wars",
    points: 600,
    clue: "In The Hobbit, this battle involves Men, Elves, and Dwarves and is interrupted by the arrival of the Eagles and Beorn.",
    correct_answer: "Battle of the Five Armies",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-800-1",
    category: "Epic Battles & Wars",
    points: 800,
    clue: "Gandalf's final words before falling into the abyss in Moria are directed at the Balrog with this phrase.",
    correct_answer: "You shall not pass!",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-1000-1",
    category: "Epic Battles & Wars",
    points: 1000,
    clue: "The War of Wrath, which ended the First Age, saw the hosts of the Valar defeat Morgoth. This massive creature allied with Morgoth was slain by Eärendil.",
    correct_answer: "Ancalagon the Black",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // ─── The Shire & Hobbit Life ──────────────────────────────────────────────
  {
    id: "sh-200-1",
    category: "The Shire & Hobbit Life",
    points: 200,
    clue: "Bilbo's underground home in the Shire is known by this name.",
    correct_answer: "Bag End",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-400-1",
    category: "The Shire & Hobbit Life",
    points: 400,
    clue: "On his eleventy-first (111th) birthday, Bilbo gives a grand party and disappears — at this hobbit age he is considered middle-aged.",
    correct_answer: "111",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-600-1",
    category: "The Shire & Hobbit Life",
    points: 600,
    clue: "Hobbits are particularly fond of this leaf product, which they call 'pipe-weed' or 'Old Toby', introduced to the Shire by the Hornblowers.",
    correct_answer: "Longbottom Leaf / pipe-weed / tobacco",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-800-1",
    category: "The Shire & Hobbit Life",
    points: 800,
    clue: "This pub in Hobbiton, where Frodo meets Gandalf's contact, is a favourite haunt of hobbits in The Fellowship of the Ring.",
    correct_answer: "The Green Dragon Inn",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-1000-1",
    category: "The Shire & Hobbit Life",
    points: 1000,
    clue: "In Tolkien's lore, Hobbits are divided into three breeds: Harfoots, Stoors, and this third group known for being tall and friendly with Elves.",
    correct_answer: "Fallohides",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // ─── Ancient Lore & Languages ─────────────────────────────────────────────
  {
    id: "all-200-1",
    category: "Ancient Lore & Languages",
    points: 200,
    clue: "J.R.R. Tolkien was a professor of this subject at Oxford University, which deeply influenced his creation of elvish languages.",
    correct_answer: "Anglo-Saxon / Old English (philology)",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-400-1",
    category: "Ancient Lore & Languages",
    points: 400,
    clue: "The elvish word 'mellon', meaning this in Sindarin, is the password to the Doors of Durin at the entrance to Moria.",
    correct_answer: "Friend",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-600-1",
    category: "Ancient Lore & Languages",
    points: 600,
    clue: "The Black Speech inscription on the One Ring was written using this elvish script system invented by Fëanor.",
    correct_answer: "Tengwar",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-800-1",
    category: "Ancient Lore & Languages",
    points: 800,
    clue: "In Tolkien's cosmology, these are the 14 godlike beings (similar to angels) who shaped the world of Arda under Ilúvatar's will.",
    correct_answer: "The Valar",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-1000-1",
    category: "Ancient Lore & Languages",
    points: 1000,
    clue: "The Silmarils, three jewels of immense power created by Fëanor, were stolen from the Trees of Valinor by this entity — Tolkien's original Dark Lord before Sauron.",
    correct_answer: "Morgoth (Melkor)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // ─── Final Jeopardy (points: 0, id: "final-jeopardy") ────────────────────
  {
    id: "final-jeopardy",
    category: "Ancient Lore & Languages",
    points: 0 as never,
    clue: "This is the name of the created language Tolkien based on Finnish phonology — the 'High-elven' tongue spoken by the Noldor and used in many of the most poetic LOTR verses.",
    correct_answer: "Quenya",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
];
