// ─── Fallback Question Bank ───────────────────────────────────────────────────
// Hardcoded questions used when Claude or The One API is unavailable.
// Each topic has 30 board questions + 1 Final Jeopardy question (id: "final-jeopardy").
// These ensure the game always works even without API keys configured.

import type { TriviaClue } from "@/types/game";
import type { TopicId } from "@/types/game";

// ─── LOTR Questions ───────────────────────────────────────────────────────────

const LOTR_QUESTIONS: TriviaClue[] = [
  // Fellowship & Heroes
  {
    id: "fh-200-1",
    category: "Fellowship & Heroes",
    points: 200,
    clue: "This hobbit is tasked with carrying the One Ring from the Shire to Mordor.",
    correct_answer: "Frodo Baggins",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-400-1",
    category: "Fellowship & Heroes",
    points: 400,
    clue: "This loyal hobbit companion of Frodo famously says, 'I can't carry it for you, but I can carry you!'",
    correct_answer: "Samwise Gamgee",
    difficulty: "medium",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-600-1",
    category: "Fellowship & Heroes",
    points: 600,
    clue: "This Ranger of the North is heir to the throne of Gondor and goes by the alias 'Strider' in the films.",
    correct_answer: "Aragorn",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-800-1",
    category: "Fellowship & Heroes",
    points: 800,
    clue: "This Rohirrim captain led Theoden's forces into battle and is Eowyn's uncle.",
    correct_answer: "Eomer",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fh-1000-1",
    category: "Fellowship & Heroes",
    points: 1000,
    clue: "In Tolkien's books, Aragorn's mother gave him this name meaning 'Hope' in Quenya when he was hidden in Rivendell.",
    correct_answer: "Estel",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Rings & Dark Powers
  {
    id: "rdp-200-1",
    category: "Rings & Dark Powers",
    points: 200,
    clue: "The inscription on the One Ring, spoken in the Black Speech of Mordor, begins with these words.",
    correct_answer: "One Ring to rule them all",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-400-1",
    category: "Rings & Dark Powers",
    points: 400,
    clue: "This creature, once a hobbit named Sméagol, murdered his cousin Déagol to possess the One Ring.",
    correct_answer: "Gollum",
    difficulty: "medium",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-600-1",
    category: "Rings & Dark Powers",
    points: 600,
    clue: "This number of Rings of Power were given to the race of Men, making them susceptible to Sauron's will.",
    correct_answer: "Nine",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-800-1",
    category: "Rings & Dark Powers",
    points: 800,
    clue: "Before being known as Sauron, this was the name of the Maia who served under Aulë the Smith.",
    correct_answer: "Mairon",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "rdp-1000-1",
    category: "Rings & Dark Powers",
    points: 1000,
    clue: "This Nazgûl lord, also known as the Witch-king of Angmar, wielded a Morgul-blade that would have turned Frodo into a wraith.",
    correct_answer: "Khamûl (or the Witch-king of Angmar)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Lands of Middle-earth
  {
    id: "lme-200-1",
    category: "Lands of Middle-earth",
    points: 200,
    clue: "This peaceful hobbit homeland is where Frodo and Bilbo begin their adventures.",
    correct_answer: "The Shire",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-400-1",
    category: "Lands of Middle-earth",
    points: 400,
    clue: "Helm's Deep, the fortress where Theoden's people make their stand in The Two Towers, is located in this kingdom.",
    correct_answer: "Rohan",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-600-1",
    category: "Lands of Middle-earth",
    points: 600,
    clue: "This ancient elvish realm, ruled by Galadriel and Celeborn, serves as a refuge for the Fellowship after Moria.",
    correct_answer: "Lothlórien",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-800-1",
    category: "Lands of Middle-earth",
    points: 800,
    clue: "The dwarven city of Erebor, home of the Lonely Mountain, was sacked by this dragon and reclaimed by Thorin's company.",
    correct_answer: "Smaug",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "lme-1000-1",
    category: "Lands of Middle-earth",
    points: 1000,
    clue: "This hidden elven city, founded by Turgon in the First Age and not depicted in the films, was destroyed by Morgoth and is the birthplace of Eärendil.",
    correct_answer: "Gondolin",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Epic Battles & Wars
  {
    id: "ebw-200-1",
    category: "Epic Battles & Wars",
    points: 200,
    clue: "This battle, fought at the gates of Mordor, ends when Frodo destroys the One Ring.",
    correct_answer: "Battle of the Black Gate",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-400-1",
    category: "Epic Battles & Wars",
    points: 400,
    clue: "Eowyn famously slays the Witch-king of Angmar during this massive battle on the fields of Gondor.",
    correct_answer: "Battle of the Pelennor Fields",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-600-1",
    category: "Epic Battles & Wars",
    points: 600,
    clue: "In The Hobbit, this battle involves Men, Elves, and Dwarves and is interrupted by the arrival of the Eagles and Beorn.",
    correct_answer: "Battle of the Five Armies",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-800-1",
    category: "Epic Battles & Wars",
    points: 800,
    clue: "Gandalf's final words before falling into the abyss in Moria are directed at the Balrog with this phrase.",
    correct_answer: "You shall not pass!",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ebw-1000-1",
    category: "Epic Battles & Wars",
    points: 1000,
    clue: "The War of Wrath, which ended the First Age, saw the hosts of the Valar defeat Morgoth. This massive creature allied with Morgoth was slain by Eärendil.",
    correct_answer: "Ancalagon the Black",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // The Shire & Hobbit Life
  {
    id: "sh-200-1",
    category: "The Shire & Hobbit Life",
    points: 200,
    clue: "Bilbo's underground home in the Shire is known by this name.",
    correct_answer: "Bag End",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-400-1",
    category: "The Shire & Hobbit Life",
    points: 400,
    clue: "On his eleventy-first (111th) birthday, Bilbo gives a grand party and disappears — leaving behind his ring for Frodo.",
    correct_answer: "111",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-600-1",
    category: "The Shire & Hobbit Life",
    points: 600,
    clue: "Hobbits are particularly fond of this leaf product, which they call 'pipe-weed' or 'Old Toby', introduced to the Shire by the Hornblowers.",
    correct_answer: "Longbottom Leaf / pipe-weed / tobacco",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-800-1",
    category: "The Shire & Hobbit Life",
    points: 800,
    clue: "This pub in Hobbiton, where the hobbits enjoy a pint before their adventures, is a favourite haunt in The Fellowship of the Ring.",
    correct_answer: "The Green Dragon Inn",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "sh-1000-1",
    category: "The Shire & Hobbit Life",
    points: 1000,
    clue: "In Tolkien's lore, Hobbits are divided into three breeds: Harfoots, Stoors, and this third group known for being tall and friendly with Elves.",
    correct_answer: "Fallohides",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Ancient Lore & Languages
  {
    id: "all-200-1",
    category: "Ancient Lore & Languages",
    points: 200,
    clue: "J.R.R. Tolkien was a professor of this subject at Oxford University, which deeply influenced his creation of elvish languages.",
    correct_answer: "Anglo-Saxon / Old English (philology)",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-400-1",
    category: "Ancient Lore & Languages",
    points: 400,
    clue: "The elvish word 'mellon', meaning this in Sindarin, is the password to the Doors of Durin at the entrance to Moria.",
    correct_answer: "Friend",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-600-1",
    category: "Ancient Lore & Languages",
    points: 600,
    clue: "The Black Speech inscription on the One Ring was written using this elvish script system invented by Fëanor.",
    correct_answer: "Tengwar",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-800-1",
    category: "Ancient Lore & Languages",
    points: 800,
    clue: "In Tolkien's cosmology, these are the 14 godlike beings (similar to angels) who shaped the world of Arda under Ilúvatar's will.",
    correct_answer: "The Valar",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "all-1000-1",
    category: "Ancient Lore & Languages",
    points: 1000,
    clue: "The Silmarils, three jewels of immense power created by Fëanor, were stolen from the Trees of Valinor by this entity — Tolkien's original Dark Lord before Sauron.",
    correct_answer: "Morgoth (Melkor)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Final Jeopardy
  {
    id: "final-jeopardy",
    category: "Ancient Lore & Languages",
    points: 0 as never,
    clue: "This is the name of the created language Tolkien based on Finnish phonology — the 'High-elven' tongue spoken by the Noldor and used in many of the most poetic LOTR verses.",
    correct_answer: "Quenya",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
];

// ─── Friends Questions ─────────────────────────────────────────────────────────

const FRIENDS_QUESTIONS: TriviaClue[] = [
  // The One Where…
  {
    id: "fw-ow-200",
    category: "The One Where…",
    points: 200,
    clue: "The pilot episode of Friends is called 'The One Where Monica Gets a ___' and introduces Rachel Green, who has just fled her own wedding.",
    correct_answer: "Roommate",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-ow-400",
    category: "The One Where…",
    points: 400,
    clue: "In 'The One with the Embryos,' Chandler and Joey beat Monica and Rachel in a trivia contest and win this prize.",
    correct_answer: "Their apartment",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-ow-600",
    category: "The One Where…",
    points: 600,
    clue: "In 'The One with the Embryos,' the quiz master reveals that Chandler's TV Guide is addressed to 'Miss Chanandler Bong' — this is the actual correct name on the subscription.",
    correct_answer: "Chanandler Bong (Miss Chanandler Bong)",
    difficulty: "hard",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-ow-800",
    category: "The One Where…",
    points: 800,
    clue: "'The One Where No One's Ready' is set entirely in Monica's apartment. Which character refuses to leave the armchair all evening, eating food and putting on all of Joey's clothes?",
    correct_answer: "Joey Tribbiani",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-ow-1000",
    category: "The One Where…",
    points: 1000,
    clue: "In 'The One That Could Have Been,' an alternate universe shows Joey still employed on his soap opera. What is the name of his fictional soap opera character?",
    correct_answer: "Dr. Drake Ramoray (Days of Our Lives)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Central Perk & The Apartment
  {
    id: "fw-cp-200",
    category: "Central Perk & The Apartment",
    points: 200,
    clue: "The Friends gang always congregates at this Greenwich Village coffee shop, which has a large orange couch.",
    correct_answer: "Central Perk",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cp-400",
    category: "Central Perk & The Apartment",
    points: 400,
    clue: "This blond-haired, lovestruck Central Perk barista has an unrequited crush on Rachel for the entire run of the series.",
    correct_answer: "Gunther",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cp-600",
    category: "Central Perk & The Apartment",
    points: 600,
    clue: "Joey and Chandler keep two beloved live pets in their apartment — a chick and a duck. What kind of animal is the chick?",
    correct_answer: "A baby chicken (chick)",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cp-800",
    category: "Central Perk & The Apartment",
    points: 800,
    clue: "The friends spy on this name given to the large, perpetually naked man who lives across the street from Monica's apartment.",
    correct_answer: "Ugly Naked Guy",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cp-1000",
    category: "Central Perk & The Apartment",
    points: 1000,
    clue: "In early seasons, Monica's apartment is labeled #5 and Chandler/Joey's is #4. Fans wrote in to point out the impossibility of those numbers for that floor, so the producers changed them to these two numbers.",
    correct_answer: "20 and 19",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Characters & Relationships
  {
    id: "fw-cr-200",
    category: "Characters & Relationships",
    points: 200,
    clue: "This Friends character is a paleontologist, has been married three times, and shouts 'We were on a break!' as his eternal defense.",
    correct_answer: "Ross Geller",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cr-400",
    category: "Characters & Relationships",
    points: 400,
    clue: "Phoebe Buffay's eccentric personality contrasts sharply with her twin sister, who is her polar opposite. Her twin's name is this.",
    correct_answer: "Ursula",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cr-600",
    category: "Characters & Relationships",
    points: 600,
    clue: "Joey Tribbiani plays the character Dr. Drake Ramoray on this fictional soap opera throughout the series.",
    correct_answer: "Days of Our Lives",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cr-800",
    category: "Characters & Relationships",
    points: 800,
    clue: "Chandler Bing's father came out as gay and performs as a Las Vegas drag show entertainer under this stage name.",
    correct_answer: "Helena Handbasket",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-cr-1000",
    category: "Characters & Relationships",
    points: 1000,
    clue: "Chandler's job is famously mysterious to the group throughout the show. His actual job title — involving data processing — is this tongue-twisting phrase.",
    correct_answer: "Statistical analysis and data reconfiguration",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Iconic Quotes
  {
    id: "fw-iq-200",
    category: "Iconic Quotes",
    points: 200,
    clue: "Phoebe Buffay's most famous original song, performed at Central Perk about a sickly feline, is titled this.",
    correct_answer: "Smelly Cat",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-iq-400",
    category: "Iconic Quotes",
    points: 400,
    clue: "Ross shouts this single word repeatedly while trying to maneuver a sofa around a tight staircase corner, in one of the show's most iconic physical comedy moments.",
    correct_answer: "PIVOT!",
    difficulty: "medium",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-iq-600",
    category: "Iconic Quotes",
    points: 600,
    clue: "Joey Tribbiani's signature four-word pickup line, always delivered with a grin, is this.",
    correct_answer: "How you doin'?",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-iq-800",
    category: "Iconic Quotes",
    points: 800,
    clue: "Ross's repeated two-word protest — his eternal defense of his one-night stand with Chloe the copy girl — became the show's most debated catchphrase.",
    correct_answer: "We were on a break!",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-iq-1000",
    category: "Iconic Quotes",
    points: 1000,
    clue: "Janice's memorable catchphrase — three single-syllable words delivered in a distinctive nasal exclamation — is quoted throughout the entire series.",
    correct_answer: "Oh. My. God!",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Love, Breakups & Drama
  {
    id: "fw-lb-200",
    category: "Love, Breakups & Drama",
    points: 200,
    clue: "Ross and Rachel's central on-again, off-again love story concludes with them finally getting together for good in the show's finale, which aired in Season ___.",
    correct_answer: "Season 10",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-lb-400",
    category: "Love, Breakups & Drama",
    points: 400,
    clue: "Monica and Chandler secretly hook up during Ross's wedding in London. In which season do they get engaged?",
    correct_answer: "Season 6",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-lb-600",
    category: "Love, Breakups & Drama",
    points: 600,
    clue: "Ross has been married three times by the show's end. His three wives, in order, are Carol, Emily, and this woman he married while drunk in Las Vegas.",
    correct_answer: "Rachel Green",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-lb-800",
    category: "Love, Breakups & Drama",
    points: 800,
    clue: "In Season 3, Ross sleeps with Chloe the copy girl on the night he and Rachel take a break. Which two friends encouraged Ross to call Chloe that night?",
    correct_answer: "Joey and Chandler",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-lb-1000",
    category: "Love, Breakups & Drama",
    points: 1000,
    clue: "In Seasons 9–10, Joey develops feelings for Rachel, creating tension. Their brief romance fizzles naturally when Rachel ultimately reunites with this person in the finale.",
    correct_answer: "Ross Geller",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Behind the Scenes
  {
    id: "fw-bs-200",
    category: "Behind the Scenes",
    points: 200,
    clue: "Friends ran for 10 seasons on this American TV network, from September 1994 to May 2004.",
    correct_answer: "NBC",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-bs-400",
    category: "Behind the Scenes",
    points: 400,
    clue: "The Friends theme song 'I'll Be There for You' was performed by this duo, who had a #1 hit with it in 1995.",
    correct_answer: "The Rembrandts",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-bs-600",
    category: "Behind the Scenes",
    points: 600,
    clue: "Friends was co-created by David Crane and this woman, who also wrote and produced the show throughout its entire run.",
    correct_answer: "Marta Kauffman",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-bs-800",
    category: "Behind the Scenes",
    points: 800,
    clue: "In the final two seasons, all six main cast members were each paid $1 million per episode after famously negotiating their salaries collectively. Who was the first among the six to receive a higher salary than the others, prompting the group negotiation?",
    correct_answer: "Jennifer Aniston (and David Schwimmer)",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "fw-bs-1000",
    category: "Behind the Scenes",
    points: 1000,
    clue: "Matthew Perry, who played Chandler Bing, passed away in October 2023. His 2022 memoir about his struggles with addiction and his time on Friends is titled this.",
    correct_answer: "Friends, Lovers, and the Big Terrible Thing",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Final Jeopardy
  {
    id: "final-jeopardy",
    category: "Behind the Scenes",
    points: 0 as never,
    clue: "The Friends series finale, 'The Last One,' aired on May 6, 2004, and drew approximately this many viewers in the United States, making it one of the most-watched TV finales in American history.",
    correct_answer: "52.5 million viewers",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
];

// ─── Animal Kingdom Questions ──────────────────────────────────────────────────

const ANIMAL_KINGDOM_QUESTIONS: TriviaClue[] = [
  // Mammals
  {
    id: "ak-m-200",
    category: "Mammals",
    points: 200,
    clue: "The largest land animal on Earth, weighing up to 14,000 lbs and bearing a distinctive trunk and large tusks, is the African ___.",
    correct_answer: "Elephant",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-m-400",
    category: "Mammals",
    points: 400,
    clue: "This marine mammal is the largest animal ever known to exist, can weigh up to 200 tons, and communicates using low-frequency vocalizations heard across ocean basins.",
    correct_answer: "Blue whale",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-m-600",
    category: "Mammals",
    points: 600,
    clue: "The platypus is unique in being a mammal that lays eggs. The only other mammals that also lay eggs are collectively known by this order name.",
    correct_answer: "Monotremes (echidnas)",
    difficulty: "hard",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-m-800",
    category: "Mammals",
    points: 800,
    clue: "The Etruscan shrew (Suncus etruscus) holds the record for the world's smallest mammal by mass, weighing less than this many grams.",
    correct_answer: "2 grams",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-m-1000",
    category: "Mammals",
    points: 1000,
    clue: "Vampire bats are one of the few animals to demonstrate reciprocal altruism: a well-fed bat will regurgitate blood to feed a hungry roost-mate who failed to feed that night. This behavior is an example of what evolutionary concept?",
    correct_answer: "Reciprocal altruism",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Birds & Reptiles
  {
    id: "ak-br-200",
    category: "Birds & Reptiles",
    points: 200,
    clue: "The fastest animal on Earth in a dive, this bird of prey reaches speeds exceeding 240 mph when stooping toward its quarry.",
    correct_answer: "Peregrine falcon",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-br-400",
    category: "Birds & Reptiles",
    points: 400,
    clue: "This large flightless bird native to Africa is the fastest running bird on Earth and lays the largest eggs of any living bird species.",
    correct_answer: "Ostrich",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-br-600",
    category: "Birds & Reptiles",
    points: 600,
    clue: "The Komodo dragon, the world's largest lizard at up to 10 feet long, is native to a group of islands in this Southeast Asian country.",
    correct_answer: "Indonesia",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-br-800",
    category: "Birds & Reptiles",
    points: 800,
    clue: "Contrary to popular belief, chameleons change color primarily for this reason — not camouflage, but rather to communicate mood and regulate temperature.",
    correct_answer: "Social signaling / communication",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-br-1000",
    category: "Birds & Reptiles",
    points: 1000,
    clue: "The tuatara, native to New Zealand and the sole survivor of an ancient reptile order, has a functional third eye on top of its head called the ___.",
    correct_answer: "Parietal eye (pineal eye)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Ocean & Aquatic Life
  {
    id: "ak-oa-200",
    category: "Ocean & Aquatic Life",
    points: 200,
    clue: "The largest fish in the ocean, known for its docile nature and distinctive white-spotted pattern, is the ___ shark.",
    correct_answer: "Whale shark",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-oa-400",
    category: "Ocean & Aquatic Life",
    points: 400,
    clue: "This highly intelligent cephalopod has three hearts, blue blood, eight arms, and can change color and texture in milliseconds.",
    correct_answer: "Octopus",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-oa-600",
    category: "Ocean & Aquatic Life",
    points: 600,
    clue: "If the dominant female clownfish in an anemone dies, the largest male will change sex and become the new female — this type of sex change is called ___.",
    correct_answer: "Sequential hermaphroditism (protandry)",
    difficulty: "hard",
    isDailyDouble: true,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-oa-800",
    category: "Ocean & Aquatic Life",
    points: 800,
    clue: "The mantis shrimp has the most complex visual system of any known animal, with up to 16 types of photoreceptors. Humans have only this many types.",
    correct_answer: "3 (three cone types)",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-oa-1000",
    category: "Ocean & Aquatic Life",
    points: 1000,
    clue: "The immortal jellyfish (Turritopsis dohrnii) can revert to its juvenile polyp stage after reaching adulthood — a process called ___.",
    correct_answer: "Transdifferentiation",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Insects & Arachnids
  {
    id: "ak-ia-200",
    category: "Insects & Arachnids",
    points: 200,
    clue: "Honeybees communicate the direction and distance of food sources to hive mates through this famous movement.",
    correct_answer: "Waggle dance",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ia-400",
    category: "Insects & Arachnids",
    points: 400,
    clue: "A parasitic fungus infects carpenter ants, controls their behavior, and forces them to climb plants before killing them to spread spores — giving rise to the nickname 'zombie ants.' The fungus responsible belongs to this genus.",
    correct_answer: "Ophiocordyceps",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ia-600",
    category: "Insects & Arachnids",
    points: 600,
    clue: "The Goliath birdeater, the world's largest spider by mass, is native to South America and belongs to this family of spiders.",
    correct_answer: "Theraphosidae (tarantulas)",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ia-800",
    category: "Insects & Arachnids",
    points: 800,
    clue: "Monarch butterflies famously migrate up to 3,000 miles each year from the United States and Canada to overwintering grounds in the mountains of this Mexican state.",
    correct_answer: "Michoacán",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ia-1000",
    category: "Insects & Arachnids",
    points: 1000,
    clue: "The bombardier beetle defends itself by mixing hydroquinone and hydrogen peroxide inside its body to produce a boiling hot explosive spray, reaching temperatures close to ___.",
    correct_answer: "100°C (the boiling point of water / 212°F)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Endangered & Extinct
  {
    id: "ak-ee-200",
    category: "Endangered & Extinct",
    points: 200,
    clue: "The dodo, a large flightless bird that became extinct in the late 17th century after sailors hunted it to oblivion, was native to this Indian Ocean island.",
    correct_answer: "Mauritius",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ee-400",
    category: "Endangered & Extinct",
    points: 400,
    clue: "A small isolated population of woolly mammoths survived on this Arctic island until around 1650 BCE, long after their mainland cousins disappeared.",
    correct_answer: "Wrangel Island",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ee-600",
    category: "Endangered & Extinct",
    points: 600,
    clue: "With fewer than 1,000 individuals remaining in the wild, this subspecies of gorilla living in the volcanic mountains of Rwanda, Uganda, and the DRC is critically endangered.",
    correct_answer: "Mountain gorilla",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ee-800",
    category: "Endangered & Extinct",
    points: 800,
    clue: "The last wild Javan rhino in Vietnam was killed by poachers in 2010. The only surviving Javan rhinos now live exclusively in this Indonesian national park.",
    correct_answer: "Ujung Kulon National Park",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ee-1000",
    category: "Endangered & Extinct",
    points: 1000,
    clue: "The thylacine (Tasmanian tiger) was declared officially extinct in 1936. The last known individual died in captivity in a zoo in this Australian city.",
    correct_answer: "Hobart (Hobart Zoo, Tasmania)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Animal Behavior & Adaptations
  {
    id: "ak-ab-200",
    category: "Animal Behavior & Adaptations",
    points: 200,
    clue: "The axolotl (Mexican salamander) is famous for its extraordinary ability to fully regenerate lost limbs, its heart, and portions of its ___.",
    correct_answer: "Brain",
    difficulty: "easy",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ab-400",
    category: "Animal Behavior & Adaptations",
    points: 400,
    clue: "Electric eels (Electrophorus electricus) can generate shocks of up to 860 volts to stun prey. They produce electricity using specialized muscle cells called ___.",
    correct_answer: "Electrocytes",
    difficulty: "medium",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ab-600",
    category: "Animal Behavior & Adaptations",
    points: 600,
    clue: "New Caledonian crows can craft hooked tools from leaves to extract grubs — a cognitive feat placing them in the same intelligence tier as great apes. This ability demonstrates what type of behavior?",
    correct_answer: "Tool use / tool manufacture",
    difficulty: "hard",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ab-800",
    category: "Animal Behavior & Adaptations",
    points: 800,
    clue: "Arctic terns (Sterna paradisaea) make the longest known animal migration, traveling from the Arctic to the Antarctic and back each year — covering approximately this distance.",
    correct_answer: "70,000 km (44,000 miles) per year",
    difficulty: "expert",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  {
    id: "ak-ab-1000",
    category: "Animal Behavior & Adaptations",
    points: 1000,
    clue: "Lyrebirds (Menura) are extraordinary mimics — they can perfectly replicate chainsaws, camera shutters, and other birds' calls. They belong to this order that includes all songbirds.",
    correct_answer: "Passeriformes",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
  // Final Jeopardy
  {
    id: "final-jeopardy",
    category: "Animal Behavior & Adaptations",
    points: 0 as never,
    clue: "The mimic octopus (Thaumoctopus mimicus), discovered in 1998 off Sulawesi, Indonesia, is unique in its ability to impersonate specific dangerous animals by reshaping its body. Name any two animals it is known to impersonate.",
    correct_answer: "Lionfish, flatfish (sole), and/or sea snake (any two)",
    difficulty: "legendary",
    isDailyDouble: false,
    isAnswered: false,
    source: "claude",
  },
];

// ─── Export keyed by TopicId ───────────────────────────────────────────────────
// question-generator.ts uses FALLBACK_QUESTIONS[topic] to get the right set.

export const FALLBACK_QUESTIONS: Record<TopicId, TriviaClue[]> = {
  lotr: LOTR_QUESTIONS,
  friends: FRIENDS_QUESTIONS,
  animal_kingdom: ANIMAL_KINGDOM_QUESTIONS,
};
